//! The reader itself.
//!
//! Small because the corpus is small, not because a GPU is slow. With no
//! pretrained English underneath it (§19, *the augury*), the corpus is the only
//! source of capability, so the model is sized against 11,243 examples rather
//! than the hardware: `d_model` 128 and two layers is ~341k parameters, about
//! 30 per example — the ratio that makes learning rather than memorising
//! plausible. Most of it is the encoder: 466 words is a 60k table against 262k
//! of attention.
//!
//! Two heads, one pass. `<cls>` carries *which command this is*; every other
//! row carries *what this word is doing in it*. Both read the same encoding,
//! because the verb and its arguments are not independent — *"put the sage in
//! the mortar"* is `grind` because of where the sage went.

use burn::nn::transformer::{
    TransformerEncoder, TransformerEncoderConfig, TransformerEncoderInput,
};
use burn::nn::{Embedding, EmbeddingConfig, Linear, LinearConfig};
use burn::prelude::*;

use crate::sample::{MAX_LEN, Tag, VERBS};

/// How wide each word's encoding is.
///
/// The one number that moves the parameter count: the encoder is quadratic in
/// it. 128 puts the model at ~341k against a corpus of 11k, which is the ratio
/// the sizing was chosen for.
pub const WIDTH: usize = 128;

/// How the reader is built.
#[derive(Config, Debug)]
pub struct ReaderConfig {
    /// Rows in the embedding table — the vocabulary plus its hash buckets.
    pub rows: usize,
    /// How many things the classifying head chooses between.
    ///
    /// A number rather than [`VERBS`], so a second reader costs no second
    /// model: the spell register asks the identical question of an identical
    /// sentence over a different set of answers, so what differs is one width
    /// and one corpus.
    #[config(default = "VERBS")]
    pub classes: usize,
    /// Encoding width.
    #[config(default = "WIDTH")]
    pub width: usize,
    /// Feed-forward width inside each layer.
    #[config(default = "WIDTH * 2")]
    pub hidden: usize,
    /// Attention heads.
    #[config(default = 4)]
    pub heads: usize,
    /// Encoder layers.
    #[config(default = 2)]
    pub layers: usize,
    /// Dropout, which matters more here than usual — a corpus generated by
    /// expanding templates repeats its sentence *shapes* many times over, and
    /// nothing else discourages the reader from memorising them.
    #[config(default = 0.1)]
    pub dropout: f64,
}

/// The reader: a sentence in, a verb and a tag per word out.
#[derive(Module, Debug)]
pub struct Reader<B: Backend> {
    /// One row per known word, plus one per hash bucket.
    words: Embedding<B>,
    /// Learned, not sinusoidal: position means something specific here — the
    /// verb at the front, the argument after it — and with 32 positions there
    /// is nothing to extrapolate to.
    places: Embedding<B>,
    body: TransformerEncoder<B>,
    /// Reads `<cls>` and a summary of what the tagger found: which command.
    ///
    /// See [`Reader::forward`] for why it is given both.
    verb: Linear<B>,
    /// Whether there is a command here at all, as its own question.
    ///
    /// It was the forty-seventh row of [`verb`](Self::verb), and one softmax
    /// cannot express *"almost certainly `grind`"* and *"almost certainly
    /// nothing"* independently — the two accuracies traded between adjacent
    /// epochs, 38.6% refusing then 93.2% (§19). Two outputs of their own,
    /// competing with nothing.
    command: Linear<B>,
    /// Reads every row: what that word is doing.
    tag: Linear<B>,
}

impl ReaderConfig {
    /// Build it, with weights not yet worth anything.
    #[must_use]
    pub fn init<B: Backend>(&self, device: &B::Device) -> Reader<B> {
        Reader {
            words: EmbeddingConfig::new(self.rows, self.width).init(device),
            places: EmbeddingConfig::new(MAX_LEN, self.width).init(device),
            body: TransformerEncoderConfig::new(self.width, self.hidden, self.heads, self.layers)
                .with_dropout(self.dropout)
                // Pre-norm: it trains more forgivingly at this depth, and nothing
                // here needs the last drop of quality that post-norm buys.
                .with_norm_first(true)
                .init(device),
            // `<cls>` plus one pooled summary per tag — see `Reader::forward`.
            verb: LinearConfig::new(self.width * (Tag::COUNT + 1), self.classes).init(device),
            command: LinearConfig::new(self.width * (Tag::COUNT + 1), 2).init(device),
            tag: LinearConfig::new(self.width, Tag::COUNT).init(device),
        }
    }
}

/// What the reader concluded about one batch.
#[derive(Debug, Clone)]
pub struct Reading<B: Backend> {
    /// Per sentence, a score for every verb. No reject row — see
    /// [`command`](Self::command).
    pub verb: Tensor<B, 2>,
    /// Per sentence, two scores: asks for nothing, or asks for something.
    ///
    /// Row 1 is *"this is a command"*. Read it before `verb`: the verb head
    /// always names its best guess, and on a sentence that asks for nothing
    /// that guess means nothing.
    pub command: Tensor<B, 2>,
    /// Per word, a score for every tag.
    pub tags: Tensor<B, 3>,
}

impl<B: Backend> Reader<B> {
    /// Read a batch of sentences.
    ///
    /// `tokens` is `[batch, MAX_LEN]` of vocabulary rows; `pad` marks which of
    /// those are padding so attention does not read them as words.
    #[must_use]
    pub fn forward(&self, tokens: Tensor<B, 2, Int>, pad: Tensor<B, 2, Bool>) -> Reading<B> {
        let [batch, length] = tokens.dims();
        let device = tokens.device();

        // 0, 1, 2 … so each row knows where it sits. Built here rather than
        // passed in: it is a fact about the shape, and a caller that got it
        // wrong would be hard to notice.
        let places = Tensor::arange(0..length as i64, &device)
            .reshape([1, length])
            .repeat_dim(0, batch);

        let encoded = self.words.forward(tokens) + self.places.forward(places);
        let encoded = self
            .body
            .forward(TransformerEncoderInput::new(encoded).mask_pad(pad.clone()));

        // `<cls>` is row zero and belongs to no word, so it is free to carry the
        // sentence's kind. Reshaped rather than squeezed: the width is read off
        // the tensor, so a change to `WIDTH` leaves no stale dimension here.
        let [_, _, width] = encoded.dims();
        let cls = encoded
            .clone()
            .slice([0..batch, 0..1])
            .reshape([batch, width]);

        let tags = self.tag.forward(encoded.clone());

        // The verb head is told what the tagger found, because the two were
        // asymmetric: tagging reads 97.1% and verbs 72.3%, so the slot
        // predictions are reliable evidence the verb head was never given.
        // (Slot-gating, in the intent/slot literature.)
        //
        // Aimed at a specific confusion: `can you take me over to the lectern`
        // came back `move lectern` rather than `attend lectern`, and what
        // separates them is how many slots are filled. Pooling per *slot*
        // rather than over the whole sentence puts that in front of the head
        // that needs it.
        let weights = burn::tensor::activation::softmax(tags.clone(), 2);
        // Padding has an encoding like anything else and must not vote. `pad` is
        // true where a row is padding, so the mask is its inverse.
        let real = pad
            .bool_not()
            .float()
            .reshape([batch, length, 1])
            .repeat_dim(2, Tag::COUNT);
        let weights = weights * real;

        // `[batch, tags, length] @ [batch, length, width]` — for each tag, the
        // encodings of the words that carry it, summed.
        let pooled = weights.clone().swap_dims(1, 2).matmul(encoded);
        // ...and normalised by how much of the sentence that tag claimed, so a
        // slot filled by four words is not four times as loud as one filled by
        // one. The floor keeps a tag nothing carries from dividing by zero.
        let mass = weights
            .sum_dim(1)
            .swap_dims(1, 2)
            .clamp_min(1.0e-6)
            .repeat_dim(2, width);
        let summary = (pooled / mass).reshape([batch, width * Tag::COUNT]);

        // Both heads read the same thing; only the question differs, so neither
        // answer costs the other any probability mass.
        let read = Tensor::cat(vec![cls, summary], 1);
        Reading {
            verb: self.verb.forward(read.clone()),
            command: self.command.forward(read),
            tags,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Vocabulary;
    use burn::backend::NdArray;

    type Cpu = NdArray<f32>;

    fn reader() -> (Reader<Cpu>, burn::backend::ndarray::NdArrayDevice) {
        let device = burn::backend::ndarray::NdArrayDevice::default();
        let rows = Vocabulary::builtin().rows();
        (ReaderConfig::new(rows).init::<Cpu>(&device), device)
    }

    #[test]
    fn it_answers_with_a_verb_per_sentence_and_a_tag_per_word() {
        let (reader, device) = reader();
        let batch = 3;
        let tokens = Tensor::<Cpu, 2, Int>::zeros([batch, MAX_LEN], &device);
        let pad = Tensor::<Cpu, 2, Bool>::empty([batch, MAX_LEN], &device);

        let reading = reader.forward(tokens, pad);
        assert_eq!(reading.verb.dims(), [batch, VERBS]);
        assert_eq!(reading.command.dims(), [batch, 2]);
        assert_eq!(reading.tags.dims(), [batch, MAX_LEN, Tag::COUNT]);
    }

    #[test]
    fn it_is_the_size_the_sizing_argument_claimed() {
        // The ratio is why the model looks like this, so it is an assertion
        // rather than a comment: ~341k against 11,243 examples is about 30
        // apiece, and ten times either way means §19's sizing argument no
        // longer describes what is built.
        let (reader, _) = reader();
        let parameters = reader.num_params();
        println!("{parameters} parameters");
        assert!(
            (150_000..600_000).contains(&parameters),
            "{parameters} parameters is not the model §19 describes"
        );
    }

    #[test]
    fn a_word_it_has_never_seen_still_has_a_row() {
        // The embedding table covers the hash buckets too, or an invented word
        // would index past the end of it — at inference, in front of a player.
        let vocabulary = Vocabulary::builtin();
        let row = vocabulary.token("zzzqqxx").row();
        assert!(
            (row as usize) < vocabulary.rows(),
            "row {row} is outside the table"
        );
    }
}
